// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vuelos.Infraestructure.EF.Contexts;

namespace Vuelos.Infraestructure.EF.Migrations
{
    [DbContext(typeof(ReadDbContext))]
    [Migration("20220502213801_InitialStructure")]
    partial class InitialStructure
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Vuelos.Infraestructure.EF.ReadModel.AeronaveReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CapacidadAsientos")
                        .HasColumnType("int")
                        .HasColumnName("capacidadAsientos");

                    b.Property<int>("CapacidadCombustible")
                        .HasColumnType("int")
                        .HasColumnName("capacidadCombustible");

                    b.Property<bool>("EsActivo")
                        .HasColumnType("bit")
                        .HasColumnName("esActivo");

                    b.Property<string>("Marca")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("marca");

                    b.Property<string>("Matricula")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("matricula");

                    b.Property<string>("Modelo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("modelo");

                    b.Property<string>("NroAeronave")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("nroAeronave");

                    b.HasKey("Id");

                    b.ToTable("Aeronave");
                });

            modelBuilder.Entity("Vuelos.Infraestructure.EF.ReadModel.AsientosAeronaveReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AeronaveId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Columna")
                        .HasColumnType("int")
                        .HasColumnName("columna");

                    b.Property<string>("EstadoAsiento")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("estadoAsiento");

                    b.Property<int>("Fila")
                        .HasColumnType("int")
                        .HasColumnName("fila");

                    b.Property<string>("NroAsiento")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("nroAsiento");

                    b.HasKey("Id");

                    b.HasIndex("AeronaveId");

                    b.ToTable("AsientosAeronave");
                });

            modelBuilder.Entity("Vuelos.Infraestructure.EF.ReadModel.AsientosAeronaveReadModel", b =>
                {
                    b.HasOne("Vuelos.Infraestructure.EF.ReadModel.AeronaveReadModel", "Aeronave")
                        .WithMany("DetalleAsientos")
                        .HasForeignKey("AeronaveId");

                    b.Navigation("Aeronave");
                });

            modelBuilder.Entity("Vuelos.Infraestructure.EF.ReadModel.AeronaveReadModel", b =>
                {
                    b.Navigation("DetalleAsientos");
                });
#pragma warning restore 612, 618
        }
    }
}
